USE practica9;

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES (
	nombre VARCHAR(30) NOT NULL,
	apellidos VARCHAR(30) NOT NULL,
	usuario VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,
	PRIMARY KEY(`password`)
) ENGINE=InnoDB DEFAULT CHARSET="UTF8";

DROP TABLE IF EXISTS TELEFONOS;
CREATE TABLE TELEFONOS (
	telefono BIGINT NOT NULL,
	password VARCHAR(30) NOT NULL,
	PRIMARY KEY(`telefono`),
	FOREIGN KEY(`password`) REFERENCES CLIENTES (`password`)
) ENGINE=InnoDB DEFAULT CHARSET="UTF8";

DROP TABLE IF EXISTS TARIFAS;
CREATE TABLE TARIFAS (
	idtipotarifa BIGINT NOT NULL,
	nombretarifa VARCHAR(30) NOT NULL,
	PRIMARY KEY(`idtipotarifa`)
) ENGINE InnoDB DEFAULT CHARSET="UTF8";

DROP TABLE IF EXISTS LLAMADAS;
CREATE TABLE LLAMADAS (
	idllamada BIGINT NOT NULL,
	telefono BIGINT NOT NULL,
	destino BIGINT NOT NULL,
	duracion BIGINT NOT NULL,
	idtipotarifa BIGINT NOT NULL,
	coste VARCHAR(30) NOT NULL,
	fecha DATE NOT NULL,
	FOREIGN KEY(`telefono`) REFERENCES TELEFONOS (`telefono`),
	FOREIGN KEY(`idtipotarifa`) REFERENCES TARIFAS (`idtipotarifa`)
) ENGINE=InnoDB DEFAULT CHARSET="UTF8";

INSERT INTO TELEFONOS VALUES(678678678,'pass');
INSERT INTO TARIFAS VALUES(1,'economica');
INSERT INTO LLAMADAS VALUES(31,678678678,2,35,1,'15$','2014-09-20');
